### ISSUE TITLE
Fix style button icon - antd

### ISSUE THREAD

**Issue by hongduclam** [yocto-erp/frontend#1]
![image](https://user-images.githubusercontent.com/9206941/88263257-ee93bc00-ccf3-11ea-8c1e-587d17c86a58.png)

**Comment by lpcanh** [comment]
This is cause by using sanitize by default of react-boilerplate

https://github.com/react-boilerplate/react-boilerplate/tree/master/docs/css#sanitizecss

And Ant Design not using it, so it make conflict in UI.

Ref b33d139531b5b3dd1c74aa7b44c31e3c76230560

**Comment by lpcanh** [comment]
We need to check after removing sanitizecss, is it effect to anything else.
