### ISSUE TITLE
Setup axios base API 

### ISSUE THREAD

**Issue by hongduclam** [yocto-erp/frontend#3]

**Comment by hongduclam** [comment]
Utilize this httpClient instance for Intecepter, API endpoint, public and private,...

**Comment by lpcanh** [comment]
test integrate with Github bot

**Comment by lpcanh** [comment]
test again for integration with Telegram github bot.

**Comment by lpcanh** [comment]
@lpcanh test reply from Telegram.

**Comment by lpcanh** [comment]
@lpcanh test reply of reply.
